### ISSUE TITLE
The new clients freeze simultanously when perhaps at some even on the geothermal map

### ISSUE THREAD

**Issue by dGr8LookinSparky** [GrangerHub/tremulous#64]
Was on GrangerLab when it happened, and it seems like everyone with the new client got this bug at the same time, and players who used older clients didn't seem to get this.
Here is the last few lines in the clientconsole and the back trace:
```
cron should have run further
[H] Unique: okay I'm off to bed
[A] ALTAiRgr: earthquake
CummingDildo entered the game
tty][New Thread 0x7fffd2949700 (LWP 6370)]

Program received signal SIGINT, Interrupt.
0x00007fffd4885760 in ?? ()
Missing separate debuginfos, use: dnf debuginfo-install cyrus-sasl-lib-2.1.26-23.fc22.x86_64 keyutils-libs-1.5.9-4.fc22.x86_64 krb5-libs-1.13.2-15.fc22.x86_64 libcom_err-1.42.12-4.fc22.x86_64 libcurl-7.40.0-8.fc22.x86_64 libidn-1.32-1.fc22.x86_64 libssh2-1.5.0-2.fc22.x86_64 nspr-4.12.0-1.fc22.x86_64 nss-3.23.0-1.0.fc22.x86_64 nss-util-3.23.0-1.0.fc22.x86_64 openldap-2.4.40-12.fc22.x86_64 openssl-libs-1.0.1k-15.fc22.x86_64
(gdb) bt
#0  0x00007fffd4885760 in ?? ()
#1  0x00007fffd48858ce in ?? ()
#2  0x00007fffd47b4d75 in ?? ()
#3  0x00007fffd47bb90c in ?? ()
#4  0x00007fffd479e463 in ?? ()
#5  0x00007fffd479f01e in ?? ()
#6  0x00007fffd47e7a20 in ?? ()
#7  0x00007fffd46bb2ac in ?? ()
#8  0x00000000005c980e in VM_CallCompiled (vm=0x2386618 <vmTable+216>, 
    args=0x7fffffffc690) at src/qcommon/vm_x86.cpp:1819
#9  0x0000000000497898 in VM_Call (vm=0x2386618 <vmTable+216>, callnum=3)
    at src/qcommon/vm.cpp:870
#10 0x000000000040b63b in CL_CGameRendering (stereo=STEREO_CENTER)
    at src/client/cl_cgame.cpp:892
#11 0x0000000000425b37 in SCR_DrawScreenField (stereoFrame=STEREO_CENTER)
    at src/client/cl_scrn.cpp:512
#12 0x0000000000425cb6 in SCR_UpdateScreen () at src/client/cl_scrn.cpp:573
#13 0x000000000041e5ff in CL_Frame (msec=15) at src/client/cl_main.cpp:3034
#14 0x00000000004512bb in Com_Frame () at src/qcommon/common.cpp:3061
#15 0x000000000049e886 in main (argc=1, argv=0x7fffffffde78)
    at src/sys/sys_main.cpp:792
```
Here is the download link for the map: http://dl.grangerhub.com/base/map-thermal.pk3

**Comment by wtfbbqhax** [comment]
This crash is in CGame QVM, you'll need to investigate the game logic.

**Comment by wtfbbqhax** [comment]
@dGr8LookinSparky I'm going to close this.
